version: '2'

networks: 
  default:
    driver: bridge
  tor:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_ip_masquerade: "false"

volumes:
  traefik-ssl:
    driver: local
  tor-hidden_services:
    driver: local
  monero-data:
    driver: local
  postgres-data:
    driver: local
  guacamole-data:
    driver: local

services:

  traefik:
    container_name: traefik
    hostname: traefik
    build: traefik/
    image: sofwerx/traefik
    restart: always
    ports:
      - 80:80
      - 443:443
    environment:
      HTTP_PORT: "80"
      HTTPS_PORT: "443"
      REST_PORT: "8080"
      EMAIL: "ian@sofwerx.org"
      DNS_DOMAIN: "swx-dev.devwerx.org"
      SUBDOMAINS: '"swx-dev.devwerx.org", "orient.swx-dev.devwerx.org", "adminer.swx-dev.devwerx.org", "guacamole.swx-dev.devwerx.org"'
    volumes:
      - traefik-ssl:/ssl
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.backend=traefik"
      - "traefik.port=8080"
      - "traefik.frontend.rule=Host:traefik.swx-dev.devwerx.org"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.frontend.entryPoints=http,https"

  orient:
    build: orient/
    image: sofwerx/orient
    restart: always
    container_name: orient
    hostname: orient
    environment:
      PEER_CONFIG: "${PEER_CONFIG}"
      NIFI_CONFIG: "{ enabled: true, url: '/nifi' }"
      SECURE_PORT: 443
      HTTP_PORT: 9999
    ports:
      - 9999:9999
    labels:
      - "traefik.backend=orient"
      - "traefik.port=9999"
      - "traefik.frontend.rule=Host:orient.swx-dev.devwerx.org"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.frontend.entryPoints=http,https"

  postgres:
    image: postgres
    restart: always
    container_name: postgres
    hostname: postgres
    environment:
      #PGDATA: /var/lib/postgresql/data
      #POSTGRES_USER: postgres
      #POSTGRES_DB: postgres
      #POSTGRES_INITDB_ARGS: "--data-checksums"
      #POSTGRES_INITDB_XLOGDIR: ...
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    labels:
      - "traefik.enable=false"

  adminer:
    image: adminer
    restart: always
    container_name: adminer
    hostname: adminer
    links:
      - postgres:db
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    labels:
      - "traefik.backend=adminer"
      - "traefik.port=8080"
      - "traefik.frontend.rule=Host:adminer.swx-dev.devwerx.org"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.frontend.entryPoints=http,https"

  guacd:
    build: guacd/
    image: sofwerx/guacd
    restart: always
    container_name: guacd
    hostname: guacd
    volumes:
      - traefik-ssl:/ssl
    ports:
      - 4822:4822

  guacamole:
    build: guacamole/
    image: sofwerx/guacamole
    restart: always
    container_name: guacamole
    hostname: guacamole
    links:
      - guacd
    volumes:
      - guacamole-data:/data
      - traefik-ssl:/ssl
    environment:
      POSTGRES_HOSTNAME: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DATABASE: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      GUACD_HOSTNAME: guacd
      GUACD_PORT: 4822
    labels:
      - "traefik.backend=guacamole"
      - "traefik.port=8080"
      - "traefik.frontend.rule=Host:guacamole.swx-dev.devwerx.org;AddPrefix:/guacamole"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.frontend.entryPoints=http,https"

  tor:
    container_name: tor
    hostname: tor
    build: tor/
    image: sofwerx/tor
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - tor-hidden_services:/var/lib/tor/hidden_services
    #ports:
      #- 9001:9001
      #- 9030:9030
      #- 9050:9050
    labels:
      - "traefik.enable=false"
    networks:
      - "default"
      - "tor"
    environment:
      ONIONBOAT_HOSTNAME: tor
      ONIONBOAT_PORT: "9050"
    restart: always
    labels:
      - "traefik.enable=false"
    logging:
      driver: json-file
      options: 
        max-size: "20k"

  monero:
    container_name: monero
    hostname: monero
    build: monero/
    image: sofwerx/monero
    cap_add:
      - IPC_LOCK
    ports:
      - 18080:18080
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - monero-data:/home/monero/.bitmonero
    networks:
      - "tor"
    restart: always
    labels:
      - "traefik.enable=false"
    logging:
      driver: json-file
      options: 
        max-size: "20k"

