version: '2'

networks: {}

volumes:
  rcloud-data:
    driver: local
  rcloud-conf:
    driver: local
  redis-data:
    driver: local
  solr-data:
    driver: local
  solr-conf:
    driver: local

services:

  redis:
    container_name: redis
    hostname: redis
    restart: always
    image: redis:3
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes

  solr:
    build: rcloud/
    image: rcloud
    restart: always
    container_name: solr
    hostname: solr
    volumes:
      - solr-data:/data/rcloud/services/solr/example/solr/rcloudnotebooks/data
      - solr-conf:/data/rcloud/services/solr/example/solr/rcloudnotebooks/conf
    command: /data/rcloud/services/solr/bin/solr start -f

  rcloud:
    build: rcloud/
    image: rcloud
    restart: always
    container_name: rcloud
    hostname: rcloud
    volumes:
      - rcloud-data:/data/rcloud/data
      - rcloud-conf:/data/rcloud/conf
    environment:
      FQDN: rcloud-dev.devwerx.org
      SOLR_HOST: solr
      REDIS_HOST: redis
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      GITHUB_USER_WHITELIST: ${GITHUB_USER_WHITELIST}
    ports:
      - 80:8080
      - 8080:8080
    depends_on:
      - redis
      - solr

